<?php

$install_lang["admin_header_geomap_change"] = "Verander kaart sleutel";
$install_lang["admin_header_geomap_edit"] = "Kaart instellingen";
$install_lang["admin_header_geomap_settings_change"] = "Verander kaart instellingen";
$install_lang["admin_header_geomap_settings_edit"] = "Kaart instellingen";
$install_lang["admin_header_list"] = "Geo kaarten";
$install_lang["driver_info"] = "Details";
$install_lang["driver_key_notrequired"] = "Sleutel is niet nodig";
$install_lang["driver_name_bingmapsv7"] = "Bing maps (API v7)";
$install_lang["driver_name_googlemaps"] = "Google maps (API v2)";
$install_lang["driver_name_googlemapsv3"] = "Google maps (API v3)";
$install_lang["driver_name_yandexmaps"] = "Yandex maps (API v1)";
$install_lang["driver_name_yandexmapsv2"] = "Yandex maps (API v2)";
$install_lang["driver_registration"] = "Krijg sleutel";
$install_lang["error_cant_save_settings"] = "Kan instellingen niet opslaan, probeer opnieuw";
$install_lang["field_amenities"] = "Voorzieningen";
$install_lang["field_default_lat"] = "Standaard breedtegraad";
$install_lang["field_default_lon"] = "Standaard lengtegraad";
$install_lang["field_default_zoom"] = "Standaard oom";
$install_lang["field_driver"] = "Kaart type";
$install_lang["field_link"] = "Machtiging";
$install_lang["field_map_gid"] = "Kaart object";
$install_lang["field_marker_icon"] = "Pictogram";
$install_lang["field_marker_icon_delete"] = "Verwijder";
$install_lang["field_regkey"] = "Sleutel  ";
$install_lang["field_show_details"] = "Toon object informatie";
$install_lang["field_status"] = "Gebruikt";
$install_lang["field_title"] = "Naam";
$install_lang["field_use_amenities"] = "Gebruik voorzieningen";
$install_lang["field_use_click_zoom"] = "Gebruik klik zoom";
$install_lang["field_use_clusterer"] = "Gebruik clusterer";
$install_lang["field_use_panorama"] = "Gebruik panorama";
$install_lang["field_use_router"] = "Gebruik router";
$install_lang["field_use_search_auto"] = "Gebruik zoeken autocomplete";
$install_lang["field_use_search_radius"] = "Gebruik zoekradius";
$install_lang["field_use_searchbox"] = "Gebruik zoekbox";
$install_lang["field_use_show_details"] = "Toon details";
$install_lang["field_use_smart_zoom"] = "Gebruik smart zoom";
$install_lang["field_use_tools"] = "Gebruik gereedschaps bar";
$install_lang["field_use_type_selector"] = "Gebruik type selecteerder";
$install_lang["field_view_type"] = "Standaard weergave";
$install_lang["header_amenity_select"] = "Voorzieningen selectie";
$install_lang["link_activate_geomap"] = "Activeer";
$install_lang["link_active_geomap"] = "Actief";
$install_lang["link_edit_driver"] = "Bewerk";
$install_lang["link_reset_all"] = "Reset alle";
$install_lang["link_select_amenities"] = "Selecteer voorzieningen";
$install_lang["link_select_amenity"] = "Selecteer Voorziening";
$install_lang["link_settings_driver"] = "Berwerk kaart instellingen";
$install_lang["link_tableicon_edit_driver"] = "Kaart sleutel";
$install_lang["link_tableicon_settings_driver"] = "Instellingen";
$install_lang["link_view_map"] = "Bekijk op kaart";
$install_lang["loading"] = "Laden …";
$install_lang["map_default"] = "Oorspronkelijke map";
$install_lang["map_example"] = "Voorbeeld";
$install_lang["map_example_1_text"] = "<img src=\"/uploads/default/maps_example_1.jpeg\" align=\"left\" hspace=\"4\">\n<b>Londen</b><br>\n<b>Tower Bridge</b> is een gecombineerde sascule en hangbruk<br>\nin Londen, England, over de rivier Thames. Het ligt dicht bij de Tower of London,<br>\nwat het zijn naam geeft. Het is uitgegroeid tot een iconish symbool van Londen";
$install_lang["map_example_2_text"] = "<img src=\"/uploads/default/maps_example_2.jpg\" align=\"left\" hspace=\"4\">\n<b>Frankrijk</b><br>\nDe <b>Eiffel Toren</b> is een ijzeren raster toren gelegen op d e Champ de Mars in Parijs. <br>\nGebouwd in 1889, het is uitgegroeid tot een wereldwijd icoon van frankrijk";
$install_lang["map_example_3_text"] = "<img src=\"/uploads/default/maps_example_3.jpg\" align=\"left\" hspace=\"4\">\n<b>Italie</b><br>\n<b>Pisa</b> is een stad in Tuscany, Centraal Italie,op de rechterover van de monding van de rivier Arno aan de lingurische zee <br> Het de hoofdstad van de provincie Pisa. <br> Piza is wereldwijd bekend om haar scheve toren (de klokkentoren van de katherdraal van de stad)";
$install_lang["map_example_4_text"] = "<img src=\"/uploads/default/maps_example_4.jpeg\" align=\"left\" hspace=\"4\">\n<b>Kasteel Neuschwanstein </b><br>\nDuits: Schloss Neuschwanstein is een 19e-eeuws<br>\nneogotische paleis op een ruwe heuvel boven het dorp Hohenschwangau in de buurt van Fussen in het zuidwesten van Beieren, Duitsland.";
$install_lang["map_example_header"] = "Europese tour";
$install_lang["map_nearest_view"] = "View nearest results";
$install_lang["map_profile_view"] = "Bekijk profiel";
$install_lang["route_add"] = "Voeg route toe";
$install_lang["route_delete"] = "Verwijder roete";
$install_lang["set_general_settings_point_text"] = "<b> Sleep de markering om een standaard punt op de kaart op te zetten </b>";
$install_lang["success_update_driver"] = "Sleutel is succesvol opgeslagen";
$install_lang["success_update_driver_settings"] = "Instellingen zijn succesvol opgeslagen";
$install_lang["text_availbale_select_amenities"] = "Beschikbaar voor selectie";

