<?php

$install_lang["block_active_users"] = "Laatste actieve gebruiker";
$install_lang["block_auth_links"] = "Auth links";
$install_lang["block_featured_users"] = "Aanbevolen gebruikers";
$install_lang["block_lang_select"] = "Taal selectie";
$install_lang["block_new_users"] = "Nieuwe gebruiker";
$install_lang["block_registration_login_form"] = "Registratie / login form";
$install_lang["param_active_users_count"] = "Tellen";
$install_lang["param_active_users_title"] = "Titel";
$install_lang["param_active_users_user_type"] = "Gebruiker type ID (0 = all)";
$install_lang["param_auth_links_right_align"] = "Rechts uitlijnen";
$install_lang["param_featured_users_count"] = "Tellen";
$install_lang["param_featured_users_title"] = "Titel";
$install_lang["param_featured_users_user_type"] = "Gebruiker type ID (0 = all)";
$install_lang["param_lang_select_right_align"] = "Rechts uitlijnen";
$install_lang["param_new_users_count"] = "Tellen";
$install_lang["param_new_users_title"] = "Titel";
$install_lang["param_new_users_user_type"] = "Gebruiker type ID (0 = all)";
$install_lang["view_active_users_big_thumbs"] = "Grote thumbs";
$install_lang["view_active_users_carousel"] = "Carrousel";
$install_lang["view_active_users_carousel_w_descr"] = "Carrousel met beschrijving";
$install_lang["view_active_users_medium_thumbs"] = "Gemiddelde thumgs";
$install_lang["view_active_users_small_thumbs"] = "Kleine thumbs";
$install_lang["view_active_users_small_thumbs_w_descr"] = "Kleine thumbs met beschrijving";
$install_lang["view_auth_links_default"] = "Standaard";
$install_lang["view_featured_users_big_thumbs"] = "Grote thumbs";
$install_lang["view_featured_users_carousel"] = "Carrousel";
$install_lang["view_featured_users_carousel_w_descr"] = "Carrousel met beschrijving";
$install_lang["view_featured_users_medium_thumbs"] = "Gemiddelde thumgs";
$install_lang["view_featured_users_small_thumbs"] = "Kleine thumbs";
$install_lang["view_featured_users_small_thumbs_w_descr"] = "Kleine thumbs met beschrijving";
$install_lang["view_lang_select_default"] = "Standaard";
$install_lang["view_new_users_big_thumbs"] = "Grote thumbs";
$install_lang["view_new_users_carousel"] = "Carrousel";
$install_lang["view_new_users_carousel_w_descr"] = "Carrousel met beschrijving";
$install_lang["view_new_users_medium_thumbs"] = "Gemiddelde thumbs";
$install_lang["view_new_users_small_thumbs"] = "Kleine thumbs";
$install_lang["view_new_users_small_thumbs_w_descr"] = "Kleine thumbs met beschrijving";
$install_lang["view_registration_login_form_login_form"] = "login form";
$install_lang["view_registration_login_form_registration_form"] = "Registratie form";
